#!/bin/bash
PITAYA_DIR="${PITAYA_LIB_PATH}";
WORKING_FOLDER=$( pwd );



## FUNCTIONS
function STDERR { cat - 1>&2; }

function UNPACK_SAMPLE {
	SAMPLE_NAME="$1"
	if [ -e "${SAMPLE_NAME}.example.php" ]; then
		if [ ! -e "${SAMPLE_NAME}.php" ]; then
			mv "${SAMPLE_NAME}.example.php" "${SAMPLE_NAME}.php";
		else
			rm "${SAMPLE_NAME}.example.php"
		fi;
	fi;
}
###






## Check Pitaya Library Path
if [ "${PITAYA_DIR}" == "" ]; then
	echo "PITAYA_LIB_PATH environmental variable is not defined!" | STDERR;
	exit 1;
fi;

## Check command
mode=$1;

if [ "${mode}" == "-c" ]; then
	shift;
	command=$1;
	case "${command}" in
		"create" )
			shift;
			ProjDir="$1";
			if [ "${ProjDir}" != "" ]; then
				mkdir "${ProjDir}";
				cd "${ProjDir}";
			fi



			if [ ! -e "./Pitaya" ]; then ln -s "${PITAYA_DIR}/src" "./Pitaya"; fi;
			if [ ! -e "./Services" ]; then mkdir Services; fi;
			if [ ! -e "./Share" ]; then mkdir Share; fi;



			find "${PITAYA_DIR}/env/http" -type f -exec cp \{\} ./ \;
#			find "${PITAYA_DIR}/env/macosx" -type f -not -name "pitaya" -exec cp \{\} ./ \;

			UNPACK_SAMPLE "cli";
			UNPACK_SAMPLE "config";
			UNPACK_SAMPLE "common";

			UNPACK_SAMPLE "config-host";
			if [ ! "$1" == "--host-base" ] && [ ! "$1" == "-host" ]; then rm "config-host.php"; else shift; fi;

			rm pitaya.bat
			exit 0;
		;;

#		"unmount" )
#			UNMOUNT_PROJ
#			exit 0;
#		;;

		"showmount" )
			mount_list=$( mount | grep $(pwd) );
			echo "${mount_list[@]}";
			exit 0;
		;;

		"destroy" )
			find "${WORKING_FOLDER}" -mindepth 1 -maxdepth 1 -not -name "." -not -name ".." -exec rm -rf \{\} \;
			exit 0;
		;;

		* )
			if [ ! "${command}" == "" ]; then
				echo "${command} is not a valid command!" | STDERR;
			fi;

			echo "Supported commands are create, destroy!" | STDERR;

			exit 1;
		;;
	esac;

	exit 0;
fi



if [ -f "${mode}" ]; then
	shift;
	count=0; while [ "$#" -gt "0" ]; do ARGS[$count]=$( echo "$1" ); shift; (( count++ )); done;
	"${PITAYA_DIR}/src/portal.sh" -entry "${mode}" "${ARGS[@]}"
elif [ ! -e "./Pitaya/portal.sh" ]; then
	count=0; while [ "$#" -gt "0" ]; do ARGS[$count]=$( echo "$1" ); shift; (( count++ )); done;
	"${PITAYA_DIR}/src/portal.sh" "${ARGS[@]}"
else
	count=0; while [ "$#" -gt "0" ]; do ARGS[$count]=$( echo "$1" ); shift; (( count++ )); done;
	./Pitaya/portal.sh "${ARGS[@]}"
fi

